- name: Récupération et affichage de la liste des VMs portées par un hyperviseur
  hosts: "{{ pve_api_host }}"
  gather_facts: no

  tasks:
    - name: Récupération de la liste des VMs de l'hyperviseur
      community.proxmox.proxmox_vm_info:
        node: "{{ pve_api_host }}"
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
      register: vminfos

    - name: Affichage de la liste de VM
      debug:
        msg: "{{ item.name }}"
      loop: "{{ vminfos.proxmox_vms }}"
      when: item.name | regex_search(pattern)
