- name: Création d'une VM routeur (sous réserve quelle n'existe pas déjà)
  hosts: "{{ pve_api_host }}"
  gather_facts: no

  tasks:
    - name: Recherche de l'existence de la VM "{{ VM_name }}"
      community.proxmox.proxmox_vm_info:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        name: "{{ VM_name }}"
        validate_certs: false
      register: vminfos

    - name: Création de la VM "{{ VM_name }}" à partir du modèle "{{ template_name }}"
      include_role:
        name: createVMfromTemplate
      vars:
        pve_VM_template: "{{ template_name }}"
        pve_node: "{{ pve_api_host }}"
        pve_api_host: "{{ pve_api_host }}"
        pve_api_user: "{{pve_api_user }}"
        pve_api_token_id: "{{ pve_api_token_id }}"
        pve_api_token_secret: "{{ pve_api_token_secret }}"
        VM_name: "{{ VM_name }}"
      when: vminfos.proxmox_vms | length == 0
      
    - name: Initialisation de l'adresse IP de la VM "{{ VM_name }}"
      include_role:
        name: setVMipAddress
      vars:
        pve_node: "{{ pve_api_host }}"
        pve_api_host: "{{ pve_api_host }}"
        pve_api_user: "{{pve_api_user }}"
        pve_api_token_id: "{{ pve_api_token_id }}"
        pve_api_token_secret: "{{ pve_api_token_secret }}"
      when: vminfos.proxmox_vms | length == 0

    - name: Ajout d'une interface réseau à la VM "{{ VM_name }}"
      include_role:
        name: addNetworkItf

      vars:
        pve_node: "{{ pve_api_host }}"
        pve_api_host: "{{ pve_api_host }}"
        pve_api_user: "{{pve_api_user }}"
        pve_api_token_id: "{{ pve_api_token_id }}"
        pve_api_token_secret: "{{ pve_api_token_secret }}"
      when: vminfos.proxmox_vms | length == 0

    - name: Démarrage VM "{{ VM_name }}"
      include_role:
        name: startVM
      vars:
        pve_api_host: "{{ pve_api_host }}"
        pve_api_user: "{{pve_api_user }}"
        pve_api_token_id: "{{ pve_api_token_id }}"
        pve_api_token_secret: "{{ pve_api_token_secret }}"
      when: vminfos.proxmox_vms | length == 0
