- name: Copie de la configuration FRR par défaut
  hosts: "{{ target }}"
  become: yes
  gather_facts: yes

  tasks:
    - name: Copie du fichier frr.conf sur le routeur
      copy:
        src: /home/ansible/scripts/cfgFiles/{{ ansible_hostname|split('-')|last }}{{ suffix }}.cfg
        dest: /etc/frr/frr.conf
